version: '3'

services:
  db:
    image: mysql:8.0.25
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3314:3306
    environment:
      MYSQL_DATABASE: wordpress_di
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: mysqld --default-authentication-plugin=mysql_native_password
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_di
    volumes:
      - ./:/var/www/html
volumes:
  db_data: {}